### ISSUE TITLE
Elastic tensors in defective supercells

### ISSUE THREAD

**Issue by FPrith** [prnvrvs/elastic_vasp#1]
I am a beginner at VASP and elastic_vasp.

To calculate elastic tensors in defective supercells that are relaxed previously, which "Crystal system" is appropriate in pre-processing?
In my calculations for defective supercells, lattice constants are fixed, and only atomic coordinates are relaxed.

Below is my examples.
(1) 2×2×2 supercell of Al (Fm-3m) with an Al vacancy: cubic symmetry or reduced symmetry?
(2) 2×2×2 supercell of ZnO (P63mc) with a neutral O vacancy: hexagonal symmetry or reduced symmetry?

**Comment by prnvrvs** [comment]
In general, Reduced symmetry is best in use for both case. However It will be interesting to see how much elastic constants will change with cubic/Hexagonal symmetry.
